import { useState, useEffect, useRef, useCallback } from 'react'
import { createPortal } from 'react-dom'
import { useSimTime } from '../time/TimeContext'
import { findIssVisiblePasses, findIssSolarTransits, findIssLunarTransits, getIssTleAgeDays, getIssDataSource, loadIssTle, loadIssArchive, SATELLITES, getActiveSatellite, setActiveSatellite } from './issEngine'
import SunWidget from './SunWidget'
import MoonWidget from './MoonWidget'
import SolarDiscView from './SolarDiscView'
import MoonPhaseView from './MoonPhaseView'
import SkyDiscWidget from './SkyDiscWidget'
import SkyView from './SkyView'
import ErrorBoundary from '../components/ErrorBoundary'

const TOKEN = import.meta.env.VITE_MAPBOX_TOKEN

function cloudLabel(pct) {
  if (pct === null) return '—'
  if (pct < 20) return `${pct}% (clear)`
  if (pct < 50) return `${pct}% (patchy)`
  return `${pct}% (cloudy)`
}

function formatDuration(s) {
  if (!s) return '—'
  const m = Math.floor(s / 60)
  const sec = s % 60
  return m ? `${m}m ${sec}s` : `${sec}s`
}

function starsFromScore(score) {
  return Math.max(0, Math.min(5, Math.ceil(score / 20)))
}

function formatPassDate(date) {
  return new Intl.DateTimeFormat(undefined, {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
  }).format(date)
}

function formatPassTime(date) {
  return new Intl.DateTimeFormat(undefined, {
    hour: 'numeric',
    minute: '2-digit',
  }).format(date)
}

function formatMag(mag) {
  if (mag == null || !isFinite(mag)) return '—'
  return mag > 0 ? `+${mag.toFixed(1)}` : mag.toFixed(1)
}

// Elevation contributes 70 pts (weather will add up to 30 when integrated)
function passScore(maxAlt) {
  return Math.round(Math.min(maxAlt / 90, 1) * 70)
}

function scoreColor(score) {
  if (score >= 55) return 'high'
  if (score >= 35) return 'mid'
  if (score >= 20) return 'low'
  return 'poor'
}

function sourceLabel(source, ageDays) {
  if (source === 'archive') return `Archive · TLE ±${ageDays != null ? ageDays.toFixed(0) : '?'}d`
  if (source === 'predicted') return `Predicted · ~${ageDays != null ? Math.round(ageDays) : '?'}d from TLE`
  return null
}

const DAY_MS = 24 * 3600 * 1000

// ── Light pollution sampling ───────────────────────────────────────────────

const BORTLE_LABELS = [
  '', 'Pristine', 'Very dark', 'Rural', 'Rural/suburban',
  'Suburban', 'Bright suburban', 'Urban', 'City sky', 'Inner city',
]

// Colors match the raster-color gradient in EclipsePage
const BORTLE_COLORS = [
  '', '#04081a', '#08122a', '#121e38', '#1c3234',
  '#323c26', '#5a4822', '#8e6c2e', '#c09b52', '#e8d094',
]

// Module-level cache — the PNG is 1440×720 grayscale where each pixel value
// is the Bortle class (1–9) derived from calibrated VIIRS nW/cm²/sr radiance.
// Generated by:  npm run bortle  (scripts/processBortle.py)
let _bortleCtx = null
let _bortleW = 0, _bortleH = 0

async function getBortleCtx() {
  if (_bortleCtx) return _bortleCtx
  const img = new Image()
  await new Promise((res, rej) => {
    img.onload = res
    img.onerror = rej
    img.src = '/bortle_2025.png'
  })
  const canvas = document.createElement('canvas')
  canvas.width = _bortleW = img.width
  canvas.height = _bortleH = img.height
  _bortleCtx = canvas.getContext('2d')
  _bortleCtx.drawImage(img, 0, 0)
  return _bortleCtx
}

function useLocationInfo(lat, lng) {
  const [info, setInfo] = useState({ elevation: null, utcOffsetSec: null, loading: false })

  useEffect(() => {
    if (lat == null || lng == null) return
    setInfo({ elevation: null, utcOffsetSec: null, loading: true })
    let cancelled = false

    Promise.all([
      fetch(`https://api.open-meteo.com/v1/elevation?latitude=${lat.toFixed(6)}&longitude=${lng.toFixed(6)}`).then(r => r.json()),
      fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat.toFixed(6)}&longitude=${lng.toFixed(6)}&timezone=auto&forecast_days=0`).then(r => r.json()),
    ]).then(([elevData, tzData]) => {
      if (cancelled) return
      setInfo({
        loading: false,
        elevation: elevData.elevation?.[0] != null ? Math.round(elevData.elevation[0]) : null,
        utcOffsetSec: tzData.utc_offset_seconds ?? null,
      })
    }).catch(() => {
      if (!cancelled) setInfo({ elevation: null, utcOffsetSec: null, loading: false })
    })

    return () => { cancelled = true }
  }, [lat, lng])

  return info
}

function useLightPollution(lat, lng) {
  const [state, setState] = useState({ loading: false, bortle: null })

  useEffect(() => {
    if (lat == null || lng == null) return
    setState({ loading: true, bortle: null })
    let cancelled = false

    ;(async () => {
      try {
        const ctx = await getBortleCtx()
        const x = Math.max(0, Math.min(_bortleW - 1, Math.floor((lng + 180) / 360 * _bortleW)))
        const y = Math.max(0, Math.min(_bortleH - 1, Math.floor((90 - lat) / 180 * _bortleH)))
        const [v] = ctx.getImageData(x, y, 1, 1).data
        if (!cancelled) setState({ loading: false, bortle: v > 0 ? v : null })
      } catch {
        if (!cancelled) setState({ loading: false, bortle: null })
      }
    })()

    return () => { cancelled = true }
  }, [lat, lng])

  return state
}

export function IssObservations({ lat, lng, onSelectPass, anchorMode = 'now' }) {
  const { simTime } = useSimTime()
  const [state, setState] = useState({ loading: false, passes: [], tleAge: null, dataSource: null, loaded: false })
  // Anchor: real current time by default; sim clock only when explicitly chosen.
  // Captured once per location so playback ticks don't trigger recomputes.
  const startTimeRef = useRef(anchorMode === 'sim' ? simTime : new Date())

  useEffect(() => {
    startTimeRef.current = anchorMode === 'sim' ? simTime : new Date()
    setState({ loading: false, passes: [], tleAge: null, dataSource: null, loaded: false })
  }, [lat, lng])

  useEffect(() => {
    if (lat == null || lng == null) return
    const startTime = startTimeRef.current
    const nearCurrent = startTime.getTime() >= Date.now() - 7 * DAY_MS
    let cancelled = false
    setState({ loading: true, passes: [], tleAge: null, dataSource: null, loaded: false })
    Promise.all([
      loadIssTle({ maxCacheMs: nearCurrent ? DAY_MS : 6 * 3600 * 1000 }),
      loadIssArchive(),
    ]).then(() => {
      if (cancelled) return
      const passes = findIssVisiblePasses(lat, lng, {
        start: startTime,
        hoursAhead: 24 * 14,
        minElevDeg: 10,
        maxPasses: 80,
      })
      const ds = getIssDataSource(startTime)
      if (cancelled) return
      setState({ loading: false, passes, tleAge: getIssTleAgeDays(startTime), dataSource: ds, loaded: true })
    }).catch(() => {
      if (!cancelled) setState({ loading: false, passes: [], tleAge: null, dataSource: null, loaded: true })
    })
    return () => { cancelled = true }
  }, [lat, lng])

  const { loading, passes, tleAge, dataSource, loaded } = state

  return (
    <div className="iss-obs-body">
      {dataSource && sourceLabel(dataSource.source, dataSource.ageDays) && (
        <p className="iss-obs-warning">{sourceLabel(dataSource.source, dataSource.ageDays)} — positions are estimated.</p>
      )}
      {tleAge != null && tleAge > 3 && dataSource?.source === 'live' && (
        <p className="iss-obs-warning">TLE data is {tleAge.toFixed(1)} days old — pass timing may drift.</p>
      )}

      {loading && (
        <div className="iss-obs-empty">
          <span className="iss-obs-spinner" />
          Calculating passes…
        </div>
      )}
      {loaded && passes.length === 0 && (
        <p className="iss-obs-empty">No visible passes above 10° in the next two weeks.</p>
      )}

      {loaded && passes.length > 0 && (
        <div className="iss-obs-list">
          {passes.map(pass => {
            const mins = Math.floor(pass.durationSec / 60)
            const secs = pass.durationSec % 60
            const score = passScore(pass.maxAlt)
            const color = scoreColor(score)
            return (
              <button
                key={pass.id}
                className="iss-obs-row"
                onClick={() => onSelectPass?.(pass)}
                title="Jump to this pass on the map"
              >
                <div className="iss-obs-left">
                  <span className="iss-obs-datetime">
                    <span className="iss-obs-date">{formatPassDate(pass.start)}</span>
                    <span className="iss-obs-time">{formatPassTime(pass.start)}</span>
                  </span>
                  <span className="iss-obs-path">
                    {pass.startDir} → {pass.maxDir} → {pass.endDir}
                    <span className="iss-obs-dur">{mins}m {String(secs).padStart(2, '0')}s</span>
                  </span>
                </div>
                <div className="iss-obs-right">
                  <span className={`iss-obs-score iss-obs-score--${color}`}>{score}</span>
                  <span className="iss-obs-elev">{pass.maxAlt.toFixed(1)}° max</span>
                </div>
              </button>
            )
          })}
        </div>
      )}
    </div>
  )
}

// ── ISS transit tab ────────────────────────────────────────────────────────

function formatTransitTime(date) {
  return new Intl.DateTimeFormat(undefined, {
    month: 'short', day: 'numeric',
    hour: 'numeric', minute: '2-digit', second: '2-digit',
  }).format(date)
}

function formatTransitDuration(ms) {
  if (!ms) return '<1s'
  const s = ms / 1000
  if (s < 1) return `${(s * 1000).toFixed(0)}ms`
  return `${s.toFixed(1)}s`
}

const TWO_WEEKS_MS = 14 * 24 * 3600 * 1000

function TransitDiscIcon({ transit }) {
  const canvasRef = useRef(null)

  const draw = useCallback(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    const W = canvas.width, H = canvas.height
    const cx = W / 2, cy = H / 2
    const R = W * 0.42

    ctx.clearRect(0, 0, W, H)

    // Disc fill + border
    ctx.beginPath()
    ctx.arc(cx, cy, R, 0, Math.PI * 2)
    if (transit.type === 'solar') {
      ctx.fillStyle = '#fef9c3'
      ctx.fill()
      ctx.strokeStyle = '#ca8a04'
    } else {
      // Moon: add a subtle gradient for depth
      const grad = ctx.createRadialGradient(cx - R * 0.25, cy - R * 0.2, R * 0.05, cx, cy, R)
      grad.addColorStop(0, '#f8fafc')
      grad.addColorStop(1, '#cbd5e1')
      ctx.fillStyle = grad
      ctx.fill()
      ctx.strokeStyle = '#94a3b8'
    }
    ctx.lineWidth = 1.5
    ctx.stroke()

    // ISS path across the disc
    const pts = transit.discPath
    if (!pts || pts.length < 2) return

    // Dashed extension lines entering/leaving the disc
    const first = pts[0], last = pts[pts.length - 1]
    const dx = last.x - first.x, dy = last.y - first.y
    const dlen = Math.sqrt(dx * dx + dy * dy)
    if (dlen > 0) {
      const ex = dx / dlen * 0.35, ey = dy / dlen * 0.35
      ctx.save()
      ctx.setLineDash([2, 2])
      ctx.strokeStyle = transit.type === 'solar' ? 'rgba(0,0,0,0.25)' : 'rgba(0,0,0,0.2)'
      ctx.lineWidth = 1.2
      ctx.beginPath()
      ctx.moveTo(cx + (first.x - ex) * R, cy - (first.y - ey) * R)
      ctx.lineTo(cx + first.x * R, cy - first.y * R)
      ctx.stroke()
      ctx.beginPath()
      ctx.moveTo(cx + last.x * R, cy - last.y * R)
      ctx.lineTo(cx + (last.x + ex) * R, cy - (last.y + ey) * R)
      ctx.stroke()
      ctx.restore()
    }

    // Solid ISS path across disc
    ctx.beginPath()
    ctx.strokeStyle = transit.type === 'solar' ? 'rgba(0,0,0,0.65)' : 'rgba(30,30,60,0.6)'
    ctx.lineWidth = 2
    ctx.lineCap = 'round'
    ctx.lineJoin = 'round'
    for (let i = 0; i < pts.length; i++) {
      const px = cx + pts[i].x * R
      const py = cy - pts[i].y * R
      if (i === 0) ctx.moveTo(px, py)
      else ctx.lineTo(px, py)
    }
    ctx.stroke()
  }, [transit])

  useEffect(() => { draw() }, [draw])

  return (
    <canvas
      ref={canvasRef}
      width={64} height={64}
      className="iss-transit-disc-icon"
    />
  )
}

function formatSimDate(date) {
  return new Intl.DateTimeFormat(undefined, {
    month: 'short', day: 'numeric', year: 'numeric',
    hour: 'numeric', minute: '2-digit',
  }).format(date)
}

function IssTransitContent({ lat, lng, onTransitPaths, onSelectTransit, onSelectPlace, anchorMode = 'now' }) {
  const { simTime } = useSimTime()
  const [type, setType] = useState('solar')
  const [altInput, setAltInput] = useState('0')
  const [altFetching, setAltFetching] = useState(false)
  const [geoLoading, setGeoLoading] = useState(false)
  const [state, setState] = useState({ loading: false, transits: [], loaded: false, calcTime: null })
  const cancelRef = useRef(null)

  // Reset results when location changes
  useEffect(() => {
    setState({ loading: false, transits: [], loaded: false, calcTime: null })
    onTransitPaths?.(null)
  }, [lat, lng])

  // Auto-fetch elevation from Open-Meteo when lat/lng changes
  useEffect(() => {
    if (lat == null || lng == null) return
    let cancelled = false
    setAltFetching(true)
    fetch(`https://api.open-meteo.com/v1/elevation?latitude=${lat.toFixed(6)}&longitude=${lng.toFixed(6)}`)
      .then(r => r.json())
      .then(d => {
        if (!cancelled && d.elevation?.[0] != null) {
          setAltInput(String(Math.round(Math.max(0, d.elevation[0]))))
        }
      })
      .catch(() => {})
      .finally(() => { if (!cancelled) setAltFetching(false) })
    return () => { cancelled = true }
  }, [lat, lng])

  const handleGetLocation = () => {
    if (!navigator.geolocation || geoLoading) return
    setGeoLoading(true)
    navigator.geolocation.getCurrentPosition(
      pos => {
        setGeoLoading(false)
        onSelectPlace?.(pos.coords.longitude, pos.coords.latitude)
      },
      () => { setGeoLoading(false) },
      { timeout: 8000 }
    )
  }

  const handleTypeChange = (t) => {
    setType(t)
    setState({ loading: false, transits: [], loaded: false })
    onTransitPaths?.(null)
  }

  const handleCalculate = () => {
    if (lat == null || lng == null) return
    cancelRef.current?.()
    const altM = parseFloat(altInput) || 0
    const searchStart = anchorMode === 'sim' ? new Date(simTime) : new Date()
    let cancelled = false
    cancelRef.current = () => { cancelled = true }
    setState({ loading: true, transits: [], loaded: false, calcTime: null })
    onTransitPaths?.(null)
    Promise.all([loadIssTle({ maxCacheMs: DAY_MS }), loadIssArchive()]).then(() => {
      if (cancelled) return
      const opts = { start: searchStart, hoursAhead: 24 * 30, altM }
      const transits = type === 'solar'
        ? findIssSolarTransits(lat, lng, opts)
        : findIssLunarTransits(lat, lng, opts)
      if (cancelled) return
      const paths = {
        centerlines: {
          type: 'FeatureCollection',
          features: transits.filter(tr => tr.path?.length > 1).map(tr => ({
            type: 'Feature',
            geometry: { type: 'LineString', coordinates: tr.path },
            properties: { transitType: tr.type },
          })),
        },
        bands: {
          type: 'FeatureCollection',
          features: transits.filter(tr => tr.band?.length > 3).map(tr => ({
            type: 'Feature',
            geometry: { type: 'Polygon', coordinates: [tr.band] },
            properties: { transitType: tr.type },
          })),
        },
      }
      onTransitPaths?.(paths)
      setState({ loading: false, transits, loaded: true, calcTime: searchStart })
    }).catch(() => {
      if (!cancelled) setState({ loading: false, transits: [], loaded: true, calcTime: searchStart })
    })
  }

  const { loading, transits, loaded, calcTime } = state
  // Stale warning only matters when anchored to the sim clock
  const isStale = anchorMode === 'sim' && loaded && calcTime &&
    Math.abs(simTime.getTime() - calcTime.getTime()) > 6 * 3600 * 1000
  const fmtLat = lat != null ? `${Math.abs(lat).toFixed(4)}° ${lat >= 0 ? 'N' : 'S'}` : '—'
  const fmtLng = lng != null ? `${Math.abs(lng).toFixed(4)}° ${lng >= 0 ? 'E' : 'W'}` : '—'

  return (
    <div className="iss-transit-content">
      {/* Solar / Lunar toggle */}
      <div className="iss-pill-row iss-pill-row--sub">
        <button className={`iss-pill${type === 'solar' ? ' iss-pill--active' : ''}`}
          onClick={() => handleTypeChange('solar')}>Solar</button>
        <button className={`iss-pill${type === 'lunar' ? ' iss-pill--active' : ''}`}
          onClick={() => handleTypeChange('lunar')}>Lunar</button>
      </div>

      {/* Location + altitude */}
      <div className="iss-transit-location">
        <div className="iss-transit-coords">
          <div className="iss-transit-coord-row">
            <span className="iss-transit-coord-label">Lat</span>
            <span className="iss-transit-coord-val">{fmtLat}</span>
          </div>
          <div className="iss-transit-coord-row">
            <span className="iss-transit-coord-label">Lng</span>
            <span className="iss-transit-coord-val">{fmtLng}</span>
          </div>
          <div className="iss-transit-coord-row">
            <span className="iss-transit-coord-label">Alt</span>
            <input
              type="number" min="0" max="8849" step="10"
              className="iss-transit-alt-input"
              value={altInput}
              onChange={e => setAltInput(e.target.value)}
              disabled={altFetching}
            />
            <span className="iss-transit-coord-unit">{altFetching ? '…' : 'm'}</span>
          </div>
        </div>
        <button
          className="iss-transit-geo-btn"
          onClick={handleGetLocation}
          disabled={geoLoading || !navigator.geolocation}
          title="Use your current GPS location"
        >
          {geoLoading ? <><span className="iss-obs-spinner" />{' '}Locating…</> : '⊙ Use my location'}
        </button>
      </div>

      {/* Start time + calculate */}
      <div className="iss-transit-start-row">
        <span className="iss-transit-start-label">From</span>
        <span className="iss-transit-start-val">
          {anchorMode === 'sim' ? formatSimDate(simTime) : `Now · ${formatSimDate(new Date())}`}
        </span>
      </div>
      <button
        className="iss-transit-calc-btn"
        onClick={handleCalculate}
        disabled={loading || lat == null || lng == null}
      >
        {loading
          ? <><span className="iss-obs-spinner" />{' '}Scanning 30 days…</>
          : 'Calculate'}
      </button>

      {isStale && (
        <p className="iss-transit-stale">Time changed — recalculate to update results.</p>
      )}

      {/* Results */}
      {loaded && transits.length === 0 && (
        <p className="iss-obs-empty">No {type} transits found in the 30 days from {formatSimDate(calcTime)}.</p>
      )}
      {loaded && transits.length > 0 && (
        <div className="iss-transit-results">
          {type === 'solar' && <p className="iss-transit-note-obs">Solar filter required to observe safely.</p>}
          <p className="iss-transit-disclaimer">Paths beyond 2 weeks are approximate.</p>
          {transits.map((tr, i) => {
            const beyond = tr.midTime.getTime() > Date.now() + TWO_WEEKS_MS
            return (
              <button
                key={i}
                className={`iss-transit-row${beyond ? ' iss-transit-row--approx' : ''}`}
                onClick={() => onSelectTransit?.(tr)}
                title="Jump to this transit on the map"
              >
                <TransitDiscIcon transit={tr} />
                <div className="iss-transit-left">
                  <span className="iss-obs-date">{formatTransitTime(tr.midTime)}</span>
                  <span className="iss-obs-path">
                    {tr.inBand
                      ? <span className="iss-transit-visible-badge">Visible from here</span>
                      : <span className="iss-transit-nearby-badge">{tr.minDistKm < 1 ? '<1' : Math.round(tr.minDistKm)} km away</span>
                    }
                    {' · '}sep {tr.minSepDeg.toFixed(3)}°
                  </span>
                </div>
                {beyond && <span className="iss-transit-approx-badge">~</span>}
              </button>
            )
          })}
        </div>
      )}
    </div>
  )
}

// ── Combined satellite panel ───────────────────────────────────────────────

export function IssSatellitePanel({ lat, lng, onSelectPass, onTransitPaths, onSelectTransit, onSelectPlace }) {
  const [tab, setTab] = useState('obs')
  const [satId, setSatId] = useState(() => getActiveSatellite().id)
  // Pass/transit searches anchor to the real current time by default; the
  // sim clock is opt-in (for exploring other dates)
  const [anchorMode, setAnchorMode] = useState('now')

  useEffect(() => {
    if (tab !== 'transit') onTransitPaths?.(null)
  }, [tab])

  function selectSat(id) {
    if (id === satId) return
    setActiveSatellite(id)
    loadIssTle()          // fetch the new satellite's TLE (cached per satellite)
    onTransitPaths?.(null)
    setSatId(id)
  }

  const sat = SATELLITES.find(s => s.id === satId) ?? SATELLITES[0]

  return (
    <div className="iss-sat-panel">
      {/* Satellite picker — the engine tracks one satellite at a time */}
      <div className="iss-sat-picker">
        <span className="eclipse-filter-label">Satellite</span>
        <div className="evt-pill-row">
          {SATELLITES.map(s => (
            <button
              key={s.id}
              className={`evt-pill${s.id === satId ? ' is-on' : ''}`}
              onClick={() => selectSat(s.id)}
            >{s.name}</button>
          ))}
        </div>
        <span className="eclipse-filter-label" style={{ marginTop: '0.25rem' }}>Search from</span>
        <div className="evt-pill-row">
          <button className={`evt-pill${anchorMode === 'now' ? ' is-on' : ''}`}
            onClick={() => setAnchorMode('now')}>Current time</button>
          <button className={`evt-pill${anchorMode === 'sim' ? ' is-on' : ''}`}
            onClick={() => setAnchorMode('sim')}>Sim clock</button>
        </div>
      </div>

      <div className="iss-sat-header">
        <span className="iss-sat-name">{sat.name}</span>
        <div className="iss-pill-row">
          <button className={`iss-pill${tab === 'obs' ? ' iss-pill--active' : ''}`}
            onClick={() => setTab('obs')}>Observations</button>
          <button className={`iss-pill${tab === 'transit' ? ' iss-pill--active' : ''}`}
            onClick={() => setTab('transit')}>Transits</button>
        </div>
      </div>

      {/* key remounts the tabs so results recompute on satellite/anchor switch */}
      {tab === 'obs' && (lat != null
        ? <IssObservations key={`${satId}-${anchorMode}`} lat={lat} lng={lng} onSelectPass={onSelectPass} anchorMode={anchorMode} />
        : <p className="iss-obs-empty" style={{ padding: '8px 12px' }}>Click a location to see passes.</p>
      )}
      {tab === 'transit' && (lat != null
        ? <IssTransitContent key={`${satId}-${anchorMode}`} lat={lat} lng={lng} onTransitPaths={onTransitPaths} onSelectTransit={onSelectTransit} onSelectPlace={onSelectPlace} anchorMode={anchorMode} />
        : <p className="iss-obs-empty" style={{ padding: '8px 12px' }}>
            Click a location or{' '}
            <button className="iss-transit-geo-inline" onClick={() => {
              if (!navigator.geolocation) return
              navigator.geolocation.getCurrentPosition(
                pos => onSelectPlace?.(pos.coords.longitude, pos.coords.latitude),
                () => {}
              )
            }}>use your location</button>
            {' '}to scan for transits.
          </p>
      )}
    </div>
  )
}

// ── Search box ─────────────────────────────────────────────────────────────

function SearchBox({ onSelectPlace }) {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState([])
  const [loading, setLoading] = useState(false)
  const [open, setOpen] = useState(false)
  const timerRef = useRef(null)
  const boxRef = useRef(null)

  // Debounced geocoding
  useEffect(() => {
    if (!query.trim()) { setResults([]); setOpen(false); return }
    clearTimeout(timerRef.current)
    timerRef.current = setTimeout(async () => {
      if (!TOKEN) return
      setLoading(true)
      try {
        const url = `https://api.mapbox.com/geocoding/v5/mapbox.places/${encodeURIComponent(query)}.json` +
          `?access_token=${TOKEN}&limit=6&types=place,locality,address,poi,region,country`
        const res = await fetch(url)
        const json = await res.json()
        setResults(json.features ?? [])
        setOpen(true)
      } catch { setResults([]) }
      setLoading(false)
    }, 280)
    return () => clearTimeout(timerRef.current)
  }, [query])

  // Close on outside click
  useEffect(() => {
    function onDown(e) {
      if (boxRef.current && !boxRef.current.contains(e.target)) setOpen(false)
    }
    document.addEventListener('mousedown', onDown)
    return () => document.removeEventListener('mousedown', onDown)
  }, [])

  function pick(feature) {
    const [lng, lat] = feature.center
    onSelectPlace(lng, lat)
    setQuery('')
    setResults([])
    setOpen(false)
  }

  return (
    <div className="lp-search" ref={boxRef}>
      <div className="lp-search-row">
        <span className="lp-search-icon">⌕</span>
        <input
          className="lp-search-input"
          placeholder="Search cities, places…"
          value={query}
          onChange={e => setQuery(e.target.value)}
          onFocus={() => results.length && setOpen(true)}
        />
        {loading && <span className="lp-search-spinner" />}
        {query && !loading && (
          <button className="lp-search-clear" onClick={() => { setQuery(''); setResults([]); setOpen(false) }}>✕</button>
        )}
      </div>
      {open && results.length > 0 && (
        <div className="lp-results">
          {results.map(f => (
            <button key={f.id} className="lp-result-row" onClick={() => pick(f)}>
              <span className="lp-result-name">{f.text}</span>
              <span className="lp-result-context">{f.place_name.split(',').slice(1).join(',').trim()}</span>
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

// ── Lazy accordion section ─────────────────────────────────────────────────

function LpSection({ title, children, resetKey, onClose }) {
  const [open, setOpen] = useState(false)

  // Collapse when location changes so stale content doesn't linger
  useEffect(() => { setOpen(false) }, [resetKey])

  function toggle() {
    setOpen(v => {
      if (v) onClose?.()
      return !v
    })
  }

  return (
    <div className="lp-section">
      <button className="lp-section-toggle" onClick={toggle}>
        <span className="lp-section-title">{title}</span>
        <span className={`lp-section-caret${open ? ' is-open' : ''}`}>▾</span>
      </button>
      {open && (
        <div className="lp-section-body">
          {typeof children === 'function' ? children() : children}
        </div>
      )}
    </div>
  )
}

// ── Location info strip ────────────────────────────────────────────────────

function fmtElev(m) {
  if (m == null) return '—'
  if (m < 0) return `${m} m`
  return `${m.toLocaleString()} m`
}

function fmtLocalTime(simTime, utcOffsetSec) {
  if (utcOffsetSec == null) return '—'
  const localMs = simTime.getTime() + utcOffsetSec * 1000
  const d = new Date(localMs)
  const h = d.getUTCHours(), m = d.getUTCMinutes()
  const ampm = h >= 12 ? 'PM' : 'AM'
  const h12 = ((h % 12) || 12)
  return `${h12}:${String(m).padStart(2, '0')} ${ampm}`
}

function LocationInfoStrip({ lat, lng, simTime }) {
  const info = useLocationInfo(lat, lng)
  const lp   = useLightPollution(lat, lng)

  const localTime = fmtLocalTime(simTime, info.utcOffsetSec)

  return (
    <div className="lp-info-strip">
      <div className="lp-info-item">
        <span className="lp-info-label">Local time</span>
        <span className="lp-info-value">{info.loading ? '…' : localTime}</span>
      </div>
      <div className="lp-info-item">
        <span className="lp-info-label">Elevation</span>
        <span className="lp-info-value">{info.loading ? '…' : fmtElev(info.elevation)}</span>
      </div>
      <div className="lp-info-item">
        <span className="lp-info-label">Light pollution</span>
        <span className="lp-info-value">
          {lp.loading ? '…' : lp.bortle != null
            ? <><span className="lp-lp-swatch" style={{ background: BORTLE_COLORS[lp.bortle] }} />Bortle {lp.bortle}</>
            : '—'
          }
        </span>
      </div>
    </div>
  )
}

// ── Main panel ─────────────────────────────────────────────────────────────

export default function LocationPanel({ scoreData, onClose, onSelectPlace, eclipseKind = 'solar' }) {
  const hasData = scoreData !== null
  const { simTime } = useSimTime()
  const [skyOpen, setSkyOpen] = useState(false)
  const skyFocus = eclipseKind === 'lunar' ? 'moon' : 'sun'
  const locationKey = scoreData ? `${scoreData.lat},${scoreData.lng}` : null

  return (
    <>
    <div className="location-panel">
      <SearchBox onSelectPlace={onSelectPlace} />

      {hasData && (
        <>
          <div className="lp-divider" />
          <div className="lp-location-header">
            <span className="lp-place-name">
              {scoreData.placeName || `${scoreData.lat.toFixed(3)}, ${scoreData.lng.toFixed(3)}`}
            </span>
            <button className="lp-close" onClick={onClose}>✕</button>
          </div>

          <LocationInfoStrip lat={scoreData.lat} lng={scoreData.lng} simTime={simTime} />

          {scoreData.inPath && (
            <>
              <div className="lp-stars">
                {'★'.repeat(starsFromScore(scoreData.score))}{'☆'.repeat(5 - starsFromScore(scoreData.score))}
                <span className="lp-score-num">{scoreData.score}/100</span>
              </div>

              <div className="lp-stats">
                <div className="lp-stat">
                  <span className="lp-stat-label">Duration</span>
                  <span className="lp-stat-value">{formatDuration(scoreData.durationSeconds)}</span>
                </div>
                <div className="lp-stat">
                  <span className="lp-stat-label">Cloud cover</span>
                  <span className="lp-stat-value">{cloudLabel(scoreData.cloudPct)}</span>
                </div>
                <div className="lp-stat">
                  <span className="lp-stat-label">Sun altitude</span>
                  <span className="lp-stat-value">{scoreData.sunAltDeg != null ? `${scoreData.sunAltDeg}°` : '—'}</span>
                </div>
              </div>

              {scoreData.yearBreakdown?.length > 0 && (
                <div className="lp-cloud-years">
                  {scoreData.yearBreakdown.map(({ year, value }) => (
                    <div key={year} className="lp-cloud-row">
                      <span className="lp-cloud-year">{year}</span>
                      <div className="lp-cloud-track">
                        <div className="lp-cloud-fill" style={{
                          width: value != null ? `${value}%` : '0%',
                          background: value == null ? '#ccc' : value < 20 ? '#22c55e' : value < 50 ? '#eab308' : '#ef4444',
                        }} />
                      </div>
                      <span className="lp-cloud-pct">{value != null ? `${value}%` : '—'}</span>
                    </div>
                  ))}
                </div>
              )}
            </>
          )}

          {scoreData.inPath && (
            <div className="lp-actions">
              <a
                href={`https://www.airbnb.com/s/${scoreData.lat.toFixed(4)},${scoreData.lng.toFixed(4)}/homes`}
                target="_blank" rel="noopener noreferrer"
                className="lp-btn"
              >Find lodging ↗</a>
            </div>
          )}

          <div className="lp-sections">
            <LpSection title="Sky view" resetKey={locationKey}
              onClose={() => setSkyOpen(false)}>
              {() => (
                <ErrorBoundary name="SkyDiscWidget">
                  <SkyDiscWidget
                    lat={scoreData.lat} lng={scoreData.lng}
                    initialFocus={skyFocus}
                    onOpen={() => setSkyOpen(true)}
                  />
                </ErrorBoundary>
              )}
            </LpSection>

            <LpSection title="Solar disc" resetKey={locationKey}>
              {() => (
                <ErrorBoundary name="SolarDiscView">
                  <SolarDiscView lat={scoreData.lat} lng={scoreData.lng} />
                </ErrorBoundary>
              )}
            </LpSection>

            <LpSection title="Sun" resetKey={locationKey}>
              {() => (
                <ErrorBoundary name="SunWidget">
                  <SunWidget lat={scoreData.lat} lng={scoreData.lng} />
                </ErrorBoundary>
              )}
            </LpSection>

            <LpSection title="Moon" resetKey={locationKey}>
              {() => (
                <>
                  <ErrorBoundary name="MoonWidget">
                    <MoonWidget lat={scoreData.lat} lng={scoreData.lng} />
                  </ErrorBoundary>
                  <ErrorBoundary name="MoonPhaseView">
                    <MoonPhaseView lat={scoreData.lat} lng={scoreData.lng} />
                  </ErrorBoundary>
                </>
              )}
            </LpSection>
          </div>
        </>
      )}
    </div>

    {/* SkyView floats to the left of the panel; portal escapes overflow-y:auto clipping */}
    {skyOpen && scoreData && createPortal(
      <ErrorBoundary name="SkyView">
        <SkyView
          lat={scoreData.lat} lng={scoreData.lng}
          initialFocus={skyFocus}
          onClose={() => setSkyOpen(false)}
        />
      </ErrorBoundary>,
      document.body
    )}
    </>
  )
}
